### ISSUE TITLE
OC22 dataset generation

### ISSUE THREAD

**Issue by moxx799** [Open-Catalyst-Project/Open-Catalyst-Dataset#50]
Hi, 
Thanks so much for your fantastic work on Open-Catalyst-Dataset.
I am interested in OC22 dataset but I need to generate some data by myself, 
Could you pull the codes about the way to generate the OC22 data?
I will be appreciated it.

Thank you!

**Comment by CifLord** [comment]
Thank you for your interest in the OC22 dataset,
We've just added the input generator to a new OC22_dataset branch which is the version of the input set generator used to make all the VASP inputs for OC22.

**Comment by moxx799** [comment]
Hi, I appreciate your excellent work.
I have a question, without using VASP, can we generate a specific material's input information excluding the label (energy and trajectory)?

**Comment by CifLord** [comment]
Hi, my apologies for not getting back sooner. In regards to input information, the only thing you would get without the help of VASP would be information regarding the position of the atoms, the identity of the atoms, and the lattice. Since the generator uses PMG, this information is stored as a pymatgen Slab object which will have info on things like miller index, the original bulk unit cell used to make the slab, etc. 

For generating an adsorbed slab which will decorate a surface with X number of an adsorbate, you can use the `MXideAdsorbateGenerator` class located in 
`Open-Catalyst-Dataset/tree/OC22_dataset/ocdata/oc22_dataset/MXide_adsorption.py`
which takes in a slab. Then use:
MXideAdsorbateGenerator.generate_random_adsorption_structure(molecule, n_adslabs) where molecule is a pymatgen Molecule object (your adsorbate) and n_adslabs is the number of random adsorbed slabs you want to retrieve. This returns a list of adsorbed slabs.

For generating bare slabs (no adsorbates) with randomly decorated vacancies on both surfaces, you can use
`Open-Catalyst-Dataset/tree/OC22_dataset/ocdata/oc22_dataset/termination_generator.py`
`get_random_clean_slabs(bulk, n_slabs, max_index, min_slab_size, min_vacuum_size)`

where bulk is a Structure object from pymatgen representing the conventional unit cell, n_slabs is number of random slabs to return as a list, max_index is the maximum Miller index you want to go up when considering random facets, min_slab_size is the thickness of the slab in Å and min_vacuum_size is the thickness of the vacuum in Å.

Let me know if you had any other questions
